### ISSUE TITLE
[question]how to add a new post?

### ISSUE THREAD

**Issue by TimoTokki** [xcatliu/jekyllcn#122]
###### What version of Jekyll are you using (`jekyll -v`)?

Jekyll 3.1.2

###### What operating system are you using?

Ubuntu 15.10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

When I was ready to update some old translations posts, I found there is a new post [Themes](https://jekyllrb.com/docs/themes/) in [jekyllrb.com](https://jekyllrb.com/), but  not in [jekyllcn.com](http://jekyllcn.com/).
###### What did you expect to see?

I want to know how to add a new post in order.

###### What did you see instead?

No new posts.

**Comment by xcatliu** [comment]
Adding a new doc is quite easy, just add a new doc file in `site/_docs/xxx.md`, then update `site/_data/docs.yml`.

However, I'd rather to sync the whole project by merging jekyllrb to jekyllcn. It's more effective and make us keep pace with jekyllrb.

It's cool if you can help me sync with jekyllrb. I would give you as much help as I can.

**Comment by TimoTokki** [comment]
Thanks for answering my question.

I think translating this website [jekyllrb.com](http://jekyllrb.com/) is not a tiring, boring task, but an interesting, cool challenge for me.I learn a lot from translating, and it`s already huge help for me.

**Comment by TimoTokki** [comment]
Sorry,  I\`m confused about merging jekyllrb to jekyllcn.

Do you mean merging jekyll/master to jekyllcn/master, so jekyllcn would keep pace with jekyllrb?
 But one is English, one is Chinese, if merged, it could add newest content in jekyllrb, but also cause a lot of conflicts by different language. 
Is my guess right? If I\`m wrong, please tell me. 

Or, just merge jekyll/master to jekyllcn/jekyll/master?

**Comment by xcatliu** [comment]
Yes I mean merging jekyll/master to jekyllcn/master.

I tried several times, it did have some conflicts, but not many. We can simply checked out all doc files to Chinese version.

The key point is ensuring deploy script still running well.

**Comment by TimoTokki** [comment]
I tried last night, and met some difficult. 

Something like posts in `site/_docs` are easy to merge, just replaced with Chinese version. 

But something like ***.rb files in `lib/jekyll`, I don\`t sure how to merge these conflicts.
I don\`t know which one is a regular update, or added for jekyllcn in particular.

**Comment by xcatliu** [comment]
I tried but I didn't find such conflicts in `/lib/*`, here is my merging step:

```shell
git checkout master
git remote add jekyll git@github.com:jekyll/jekyll.git
git fetch --all
git checkout -b sync
git merge jekyll/master
git stataus
```

And here is conflicting files:

```shell
Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:      .travis.yml
        both modified:      site/_docs/configuration.md
        both modified:      site/_docs/continuous-integration.md
        both modified:      site/_docs/deployment-methods.md
        both modified:      site/_docs/history.md
        both modified:      site/_docs/plugins.md
        both modified:      site/_docs/posts.md
        both modified:      site/_docs/resources.md
        both modified:      site/_docs/structure.md
        both modified:      site/_docs/templates.md
        both modified:      site/_docs/troubleshooting.md
        both modified:      site/_docs/windows.md
```

Maybe you can describe your steps, or upload some of your codes?

**Comment by TimoTokki** [comment]
Sorry, I didn\`t say it clearly.

Following your steps, I got the same resaults. Surely, the files in `lib/` were auto-merged, no conflicts, but there must be some merged files not as we wish. I mean, some files must be not merged correctly. As you know, if you `bundle exec rake site:preview` now, it would fail, as following:
```
Running Jekyll...
Configuration file: /home/adidas/documents/test/jekyllcn/site/_config.yml
            Source: /home/adidas/documents/test/jekyllcn/site
       Destination: /home/adidas/documents/test/jekyllcn/site/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
rake aborted!
NoMethodError: undefined method `content' for #<Jekyll::StaticFile:0x000000037366f0>
/var/lib/gems/2.1.0/gems/jemoji-0.5.1/lib/jemoji.rb:34:in `emojify'
/var/lib/gems/2.1.0/gems/jemoji-0.5.1/lib/jemoji.rb:30:in `block in generate'
/var/lib/gems/2.1.0/gems/jemoji-0.5.1/lib/jemoji.rb:30:in `each'
/var/lib/gems/2.1.0/gems/jemoji-0.5.1/lib/jemoji.rb:30:in `generate'
/home/adidas/documents/test/jekyllcn/lib/jekyll/site.rb:171:in `block in generate'
/home/adidas/documents/test/jekyllcn/lib/jekyll/site.rb:170:in `each'
/home/adidas/documents/test/jekyllcn/lib/jekyll/site.rb:170:in `generate'
/home/adidas/documents/test/jekyllcn/lib/jekyll/site.rb:75:in `process'
/home/adidas/documents/test/jekyllcn/lib/jekyll/command.rb:26:in `process_site'
/home/adidas/documents/test/jekyllcn/lib/jekyll/commands/build.rb:60:in `build'
/home/adidas/documents/test/jekyllcn/lib/jekyll/commands/build.rb:33:in `process'
/home/adidas/documents/test/jekyllcn/rake/site.rake:31:in `block (2 levels) in <top (required)>'
Tasks: TOP => site:preview
(See full trace by running task with --trace)
```
So, after
```
git checkout master
git remote add jekyll git@github.com:jekyll/jekyll.git
git fetch --all
git checkout -b sync 
```
I use `git diff jekyll/master --stat` to check details, as following:
```
 . .travis.jekyll.yml                                          |  52 ++++++
 .travis.yml                                                 |  56 +-----
 Gemfile                                                     |   1 -
 History.markdown                                            |  15 --
 README.jekyll.markdown                                      |  58 ++++++
 README.markdown                                             |  58 ------
 README.md                                                   | 138 ++++++++++++++
 deploy_key.enc                                              | Bin 0 -> 3248 bytes
 features/frontmatter_defaults.feature                       |  20 --
 features/support/formatter.rb                               |   4 +-
 features/theme.feature                                      |  61 -------
 jekyll.gemspec                                              |   2 +-
 lib/jekyll.rb                                               |   3 +-
 lib/jekyll/collection.rb                                    |   4 +-
 lib/jekyll/configuration.rb                                 |   4 +-
 lib/jekyll/convertible.rb                                   |   8 +-
 lib/jekyll/document.rb                                      |   2 +-
 lib/jekyll/entry_filter.rb                                  |   6 +-
 lib/jekyll/filters.rb                                       |   4 -
 lib/jekyll/layout.rb                                        |  17 +-
 lib/jekyll/page.rb                                          |   1 -
 lib/jekyll/plugin_manager.rb                                |   8 +-
 lib/jekyll/readers/data_reader.rb                           |   5 +-
 lib/jekyll/readers/layout_reader.rb                         |  22 +--
 lib/jekyll/renderer.rb                                      |   3 +-
 lib/jekyll/site.rb                                          |  23 +--
 lib/jekyll/tags/include.rb                                  |  64 ++++---
 lib/jekyll/theme.rb                                         |  56 ------
 lib/site_template/_config.yml                               |   2 +-
 rake/site.rake                                              |   4 +-
 site/CNAME                                                  |   2 +-
 site/_config.yml                                            |  18 +-
 site/_data/docs.yml                                         |  13 +-
 site/_docs/assets.md                                        |  60 ++----
 site/_docs/collections.md                                   | 151 ++++++---------
 site/_docs/configuration.md                                 | 455 ++++++++++++++++++---------------------------
 site/_docs/continuous-integration.md                        | 181 +++++-------------
 site/_docs/datafiles.md                                     |  65 +++----
 site/_docs/deployment-methods.md                            | 199 ++++----------------
 site/_docs/drafts.md                                        |  13 +-
 site/_docs/extras.md                                        |  21 +--
 site/_docs/frontmatter.md                                   |  89 +++------
 site/_docs/github-pages.md                                  | 192 +++++++++----------
 site/_docs/history.md                                       |   6 -
 site/_docs/index.md                                         |  51 ++----
 site/_docs/installation.md                                  |  96 ++++------
 site/_docs/migrations.md                                    |   7 +-
 site/_docs/pages.md                                         |  70 +++----
 site/_docs/pagination.md                                    | 106 ++++-------
 site/_docs/permalinks.md                                    | 117 +++++-------
 site/_docs/plugins.md                                       | 821 ++++++++++++++++------------------------------------------------------------------
 site/_docs/posts.md                                         | 167 +++++------------
 site/_docs/quickstart.md                                    |  19 +-
 site/_docs/resources.md                                     |  58 +++---
 site/_docs/sites.md                                         |  25 ++-
 site/_docs/static_files.md                                  |  24 ++-
 site/_docs/structure.md                                     |  91 +++------
 site/_docs/templates.md                                     | 329 ++++++++++++++-------------------
 site/_docs/themes.md                                        |  89 ---------
 site/_docs/troubleshooting.md                               | 214 ++++++----------------
 site/_docs/upgrading.md                                     | 119 +++++++++++-
 site/_docs/upgrading/0-to-2.md                              |   2 +-
 site/_docs/upgrading/2-to-3.md                              |   2 +-
 site/_docs/usage.md                                         |  82 ++++-----
 site/_docs/variables.md                                     | 173 +++++++-----------
 site/_docs/windows.md                                       |  79 ++++----
 site/_includes/analytics.html                               |   6 +-
 site/_includes/docs_option.html                             |  12 +-
 site/_includes/docs_ul.html                                 |  16 +-
 site/_includes/footer.html                                  |  11 ++
 site/_includes/header.html                                  |   7 +
 site/_includes/primary-nav-items.html                       |  13 +-
 site/_includes/section_nav.html                             |   8 +-
 site/_includes/top.html                                     |   2 +-
 site/_layouts/docs.html                                     |  16 +-
 site/_posts/2015-01-24-jekyll-3-0-0-beta1-released.markdown |   2 +-
 site/_posts/2016-04-19-jekyll-3-0-4-released.markdown       |  24 ---
 site/_posts/2016-04-19-jekyll-3-1-3-released.markdown       |  18 --
 site/_posts/2016-04-26-jekyll-3-0-5-released.markdown       |  25 ---
 site/_sass/_jekyllcn.scss                                   |  46 +++++
 site/css/screen.scss                                        |   2 +
 site/index.html                                             |  32 ++--
 test/fixtures/test-theme/_includes/include.html             |   1 -
 test/fixtures/test-theme/_layouts/default.html              |   1 -
 test/fixtures/test-theme/_sass/style.scss                   |   3 -
 test/fixtures/test-theme/_symlink                           |   1 -
 test/fixtures/test-theme/test-theme.gemspec                 |   9 -
 test/test_collections.rb                                    |   8 +-
 test/test_document.rb                                       |   2 +-
 test/test_entry_filter.rb                                   |  16 +-
 test/test_site.rb                                           |   8 +-
 test/test_tags.rb                                           |   8 +-
 test/test_theme.rb                                          |  65 -------
 93 files changed, 1896 insertions(+), 3373 deletions(-)
```
Then,
```
git merge jekyll/master
git add .
git commit -m 'Update'
git diff jekyll/master
```
Resaults as following:
```
 .travis.jekyll.yml                    |  52 ++++++++
 .travis.yml                           |  27 ++--
 README.jekyll.markdown                |  58 +++++++++
 README.markdown                       |  58 ---------
 README.md                             | 138 ++++++++++++++++++++
 deploy_key.enc                        | Bin 0 -> 3248 bytes
 rake/site.rake                        |   2 +-
 site/CNAME                            |   2 +-
 site/_config.yml                      |  16 ++-
 site/_data/docs.yml                   |  12 +-
 site/_docs/assets.md                  |  60 +++------
 site/_docs/collections.md             | 151 ++++++++--------------
 site/_docs/configuration.md           | 457 ++++++++++++++++++++++++++--------------------------------------
 site/_docs/continuous-integration.md  | 173 ++++++++-----------------
 site/_docs/datafiles.md               |  65 ++++------
 site/_docs/deployment-methods.md      | 127 ++++++------------
 site/_docs/drafts.md                  |  13 +-
 site/_docs/extras.md                  |  21 ++-
 site/_docs/frontmatter.md             |  89 ++++---------
 site/_docs/github-pages.md            | 192 +++++++++++++--------------
 site/_docs/index.md                   |  51 +++-----
 site/_docs/installation.md            |  88 +++++--------
 site/_docs/migrations.md              |   7 +-
 site/_docs/pages.md                   |  66 +++-------
 site/_docs/pagination.md              | 106 ++++++---------
 site/_docs/permalinks.md              | 117 ++++++-----------
 site/_docs/plugins.md                 | 738 +++++++++++++++++++++++---------------------------------------------------------------------------------
 site/_docs/posts.md                   | 161 +++++++----------------
 site/_docs/quickstart.md              |  17 +--
 site/_docs/resources.md               |  54 +++++---
 site/_docs/sites.md                   |  25 ++--
 site/_docs/static_files.md            |  24 ++--
 site/_docs/structure.md               |  93 +++++--------
 site/_docs/templates.md               | 311 +++++++++++++++++++-------------------------
 site/_docs/troubleshooting.md         | 142 ++++++++++----------
 site/_docs/upgrading.md               | 119 ++++++++++++++++-
 site/_docs/usage.md                   |  74 +++++------
 site/_docs/variables.md               | 173 ++++++++++---------------
 site/_docs/windows.md                 |  36 ++++++
 site/_includes/analytics.html         |   6 +-
 site/_includes/footer.html            |  11 ++
 site/_includes/header.html            |   7 +
 site/_includes/primary-nav-items.html |  13 +-
 site/_includes/section_nav.html       |   8 +-
 site/_includes/top.html               |   2 +-
 site/_layouts/docs.html               |  16 ++-
 site/_sass/_jekyllcn.scss             |  46 +++++++
 site/css/screen.scss                  |   2 +
 site/index.html                       |  32 ++---
 49 files changed, 1825 insertions(+), 2433 deletions(-)
```

**Comment by TimoTokki** [comment]
Some diff like '.travis.yml', 'README.md' are easy to correct. But the diff in '/lib/', I met difficult.

**Comment by xcatliu** [comment]
As far as I can see, the problem was not about merging `lib/`, but merging `site/_docs`. I think probably you were using a wrong way to resolve conflicts.

Actually, When we got conflicts like this:

```shell
Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:      .travis.yml
        both modified:      site/_docs/configuration.md
        both modified:      site/_docs/continuous-integration.md
        both modified:      site/_docs/deployment-methods.md
        both modified:      site/_docs/history.md
        both modified:      site/_docs/plugins.md
        both modified:      site/_docs/posts.md
        both modified:      site/_docs/resources.md
        both modified:      site/_docs/structure.md
        both modified:      site/_docs/templates.md
        both modified:      site/_docs/troubleshooting.md
        both modified:      site/_docs/windows.md
```

We cannot simply executing `git add .` because git automatically edited those files by adding some lines to help you resolve conflicts.

If you execute `git diff site/_docs/configuration.md` or open `site/_docs/configuration.md` with editor, you will see something like this:

```
<<<<<<< HEAD
Jekyll 提供了一个方法在站点配置中设置这些默认值，而不是在每次创建一个新的文章或页面重复此配置。要做到这一点，你可以在项目根目录下的 `_config.yml` 文件里设置 `defaults` 的值指定全站范围的默认值。
=======
Instead of repeating this configuration each time you create a new post or page, Jekyll provides a way to set these defaults in the site configuration. To do this, you can specify  site-wide defaults using the `defaults` key in the `_config.yml` file in your project's root directory.
>>>>>>> jekyll/master
```

**You should not add such contents into git stage.**

The right way is keeping one of the two contents, and deleting another. Then `git add` and `git commit`

BTW, there is another way which is easier:

```shell
git checkout master <filepath>
```

This command can replace files by pulling them from *master* branch.

stackoverflow add google may have more solutions about resolving conflicts.

**Comment by TimoTokki** [comment]
Thanks for your patience and advice.

And with your advice\` help, I found my mistakes.

After merging, I just merged the conflicts in '.travis.yml' and used `git checkout master ./site/_docs` to merge other conflicts, then magic happened!

**Comment by xcatliu** [comment]
You are welcome!
